import login from './src/login'
import register1 from './src/register1'
import register2 from './src/register2'
import regOver from './src/regOver'
import forget1 from './src/forget1'
import forget2 from './src/forget2'
import changeMobile1 from './src/changeMobile1'
import changeMobile2 from './src/changeMobile2'
import login2 from './src/login2'
import firstPayPassword from './src/firstPayPassword'
export default { login, register1, register2, regOver, forget1, forget2, changeMobile1, changeMobile2, login2, firstPayPassword}
